version: '3'

services: 
    app: &app
        build: 
            network: host
            context: .
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - postgres
            - rabbitmq
            - celery_worker
        ports:
            - "8000:8000"
        image: app-image

    rabbitmq:
        image: rabbitmq:3.7-alpine
    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres:latest
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - "5432:5432"
        restart: on-failure
        volumes:
          - postgresql-data:/var/lib/postgresql/data
        
    celery_worker:
        <<: *app
        command: celery -A task_project worker --loglevel=info
        ports: []
        depends_on:
            - rabbitmq
            - postgres



volumes:
    postgresql-data:
